language: php
php:
- '7.0'
- '7.2'

install:
- composer install
- npm install

script:
- phpunit tests
- sonar-scanner

addons:
  sonarcloud:
    organization: "privrja-github" # the key of the org you chose at step #3
    token:
      secure: 0127d472acc40c6b4f7af12e81c6b577d0eee064 # encrypted value of your token
